@istest
public class testclasstest {
    @istest
    public static void tesct(){
        list<account> accs=new list<account>();
        account acc=new account();
        acc.Name='Hemanth';
        acc.AccountNumber='12345';
        insert acc;
        accs.add(acc);
         account ac=new account();
        ac.Name='Hemanth';
        ac.AccountNumber='12345';
        insert ac;
        accs.add(ac);
        testclasslearning.methoddd(accs);
    }
}